CREATE TABLE JOBS(
	JOB_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	JOB_CODE AS 'JOB-' + RIGHT('0' + CAST(JOB_ID AS VARCHAR(8)), 8) PERSISTED, --VARCHAR(8) NOT NULL,
	JOB_TITLE VARCHAR(100),
	JOB_DESCRIPTION VARCHAR(1000),
	POSTED_DATE DATETIME,
	CLOSING_DATE DATETIME,
	LOCATION_ID INT FOREIGN KEY REFERENCES LOCATIONS(LOCATION_ID),
	DEPARTMENT_ID INT FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)

CREATE TABLE LOCATIONS(
	LOCATION_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	LOCATION_TITLE VARCHAR(100),
	LOCATION_CITY VARCHAR(100),
	LOCATION_STATE VARCHAR(100),
	LOCATION_COUNTRY VARCHAR(100),
	LOCATION_ZIP INTEGER
)

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	DEPARTMENT_TITLE VARCHAR(100)
)